version: 2
jobs:
  build:
    docker:
      - image: uochan/vim:latest
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/thinca/vim-themis .vim-themis
            ./.vim-themis/bin/themis
